spring:
  application:
    name: Citad-Code

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/citad
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: demo_citad
    show-sql: true
